before_script:
  - docker info

build test jar:
  script:
    - gradle clean build -Denv=test
    - docker build -t gitlab.blockshine.net:4567/webplatform/open-platform:test .
    - docker push gitlab.blockshine.net:4567/webplatform/open-platform:test
  only:
    - test

build prd jar:
  script:
    - gradle clean build -Denv=prd
    - docker build -t gitlab.blockshine.net:4567/webplatform/open-platform:latest .
    - docker push gitlab.blockshine.net:4567/webplatform/open-platform:latest
  only:
    - master
